### PR TITLE
Add initial sqlite3 support.

### PR DESCRIPTION
**Pull request by sjamaan**
Since sqlite3 support comes shipped with Python, there are no additional
dependencies, so this should work easily out of the box.

### CODE REVIEW

**Comment by aartur** [comment]
Looks good.

"Dealing with dialect differences" - it's just a description of how one directory with migration files can be shared between different database engines? No new functionality implemented in code here?

I think I'll merge it tomorrow and maybe make a few docs improvements.

**Comment by sjamaan** [comment]
> "Dealing with dialect differences" - it's just a description of how one directory with migration files can be shared between different database engines? No new functionality implemented in code here?

There's a small difference: I added the ability to add files with `.sql3` and `.psql` extensions, so that you can write `.sql` files in projects that support both engines where the syntax is the same, but in cases where it differs, you can use the `.sql3 or`.psql`extension`. I'm not sure how useful this is in practice, because sqlite and postgres use pretty different DDL syntax, so feel free to revert that bit.

**Comment by sjamaan** [comment]
By the way, I just ran into this little gem: [Python's sqlite3 module breaks sqlite's transactional DDL support](http://bugs.python.org/issue10740).  This is **extremely** annoying, and probably deserves mention somewhere in the documentation. Any idea where would be a good place to add a note?

**Comment by aartur** [comment]
Ok, so I've made 0.7 release with the changes.

You can check the CHANGES file for specifics. "Dialect differences" solution should be quite workable now.

**Comment by sjamaan** [comment]
Thanks, this looks good!

One minor nitpick: I usually use `.sqlite3` as the extension of the SQLite **database file**, not the migrations. I'm not sure if this will cause any trouble in practice, because usually you'd keep the migrations in their own directory anyway.

**Pull request merged**
